apiVersion: v1
kind: Service
metadata:
  name: crudbackend
  labels:
    app: crudbackend
    service: crudbackend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: crudbackend